### ISSUE TITLE
A server error occurred when retrieving rate limit information

### ISSUE THREAD

**Issue by scottishwormboy** [enasequence/webin-cli#106]
I'm trying to submit an annotated genome assembly. webin-cli v6.5.0
The files pass when I use -validate -test but when I try to submit I get warnings
"WARN : Retrying submission rate limiting check on server."
followed by the error
"A server error occurred when retrieving rate limit information"
(The same occurs when I try just -validate w/o the -test flag)

This has persisted for about a week, tried from our cluster and from my laptop. (I have successfully submitted reads on a separate project with the same .jar file so I don't think its a problem with firewalls)

java -Xms2G -jar $HOME/miniconda3/envs/submission/share/webin-cli/webin-cli-6.5.0.jar -username Webin-XXXX -password XXXXX -context genome -manifest manifest.1.txt -submit

cat  /pub34/stevep11/Datafiles/Fasciola/pacbio22/HiC/SPdata_23/submission/./webin-cli.report
2023-07-17T12:16:51 INFO : Expiry of JWT is : Mon Jul 17 17:16:51 BST 2023
2023-07-17T12:16:51 INFO : Refresh set to : Mon Jul 17 16:16:51 BST 2023
2023-07-17T12:16:51 INFO : jwt = Optional[eyJhbGciOiJSUzI1NiJ9.eyJwcmluY2lwbGUiOiJXZWJpbi01OTk1MiIsInJvbGUiOltdLCJleHAiOjE2ODk2MTA2MTEsImlhdCI6MTY4OTU5MjYxMX0.hsP6X5um6ivcFcqs7u5sZxnjcwqRaqQyrADFDqxwfcKeHowXWbFIseXSNT1x0vRKF8ptvvoqsWTTbLZnmosKMHsgJCk_iZ3GQJHTa3crAWQAB1UEGF7dYYVlP2Ulp5LP4jDQv9xLoGbsxo_kK0yTTvNPF_Sav24BujegDutGAjMXjC6wGN6Z7RQCQdMHAI7XXoBJOW9e4_FxCKgXFOtqi1kuO4DInoZPda9O55bHV94QHtTBDPjglnfc4BPwc4rG_vSIQQrSDeUDTWqMGpRHfnOAlxL4WcKVhY_0xb5HNFblTJh5oG-06JnSrTjIQg4I5yVOXqB__M17361gn_SEJg]
2023-07-17T12:16:51 INFO : Submission has not been validated previously.
2023-07-17T12:16:53 WARN : Retrying submission rate limiting check on server.
2023-07-17T12:16:56 WARN : Retrying submission rate limiting check on server.
2023-07-17T12:17:01 WARN : Retrying submission rate limiting check on server.
2023-07-17T12:17:06 WARN : Retrying submission rate limiting check on server.
2023-07-17T12:17:11 WARN : Retrying submission rate limiting check on server.
2023-07-17T12:17:16 WARN : Retrying submission rate limiting check on server.
2023-07-17T12:17:17 ERROR: Submission validation failed because of a system error : A server error occurred when retrieving rate limit information.. Please check validation reports for further information: /pub34/stevep11/Datafiles/Fasciola/pacbio22/HiC/SPdata_23/submission/genome/FhHiC23/validate
uk.ac.ebi.ena.webin.cli.WebinCliException: Submission validation failed because of a system error : A server error occurred when retrieving rate limit information.. Please check validation reports for further information: /pub34/stevep11/Datafiles/Fasciola/pacbio22/HiC/SPdata_23/submission/genome/FhHiC23/validate
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:303)
        at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:259)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:109)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: A server error occurred when retrieving rate limit information.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.checkGenomeSubmissionRatelimit(WebinCliExecutor.java:163)
        at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.validateSubmission(WebinCliExecutor.java:100)
        at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:286)
        ... 11 common frames omitted
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: A server error occurred when retrieving rate limit information.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.utils.ExceptionUtils.executeWithRestExceptionHandling(ExceptionUtils.java:55)
        at uk.ac.ebi.ena.webin.cli.service.RatelimitService.ratelimit(RatelimitService.java:66)
        at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.checkGenomeSubmissionRatelimit(WebinCliExecutor.java:161)
        ... 13 common frames omitted
Caused by: org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error
        at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:586)
        at uk.ac.ebi.ena.webin.cli.service.RatelimitService.lambda$null$0(RatelimitService.java:69)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.lambda$executeWithRetry$0(RetryUtils.java:65)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.executeWithRetry(RetryUtils.java:60)
        at uk.ac.ebi.ena.webin.cli.service.RatelimitService.lambda$ratelimit$2(RatelimitService.java:68)
        at uk.ac.ebi.ena.webin.cli.utils.ExceptionUtils.executeWithRestExceptionHandling(ExceptionUtils.java:45)
        ... 15 common frames omitted
        
        this directory is empty
        /pub34/stevep11/Datafiles/Fasciola/pacbio22/HiC/SPdata_23/submission/genome/FhHiC23/validate

**Comment by baileyp1** [comment]
Hello, I get the same error as the scottishwormboy - I'm using version 6.5.0. Meanwhile, I'll try version 6.0.0.
Paul B.

Here are my error messages:
more webin-cli.report
2023-07-25T13:33:25 INFO : Expiry of JWT is : Tue Jul 25 18:33:25 BST 2023
2023-07-25T13:33:25 INFO : Refresh set to : Tue Jul 25 17:33:25 BST 2023
2023-07-25T13:33:25 INFO : jwt = Optional[eyJhbGciOiJSUzI1NiJ9.eyJwcmluY2lwbGUiOiJXZWJpbi01Mjk5NSIsInJvbGUiOltdLCJleHAiOjE2OTAzMDY0MDUsImlhdCI6MTY5MDI4ODQwNX0.BWGA7JwzCDvKOBugzah4Di1PNgPavPm-DrM-YkxMx35FGZBrQw2vldwgdIJCPu_A3ApZQYwayoLbvsFyA3N8_OymqUEtRjtq7-NpXSJARo_uo_cvzeGKHrBGfj8pJFgLAcSvTdvZSnszJfUOtN5r9YGInIXl_3i50tPdMV7KHSMODKniVOBNOgaV8ZBAjQo05fJKMvJgdZqP78ck_b858XiLUyGY6_gdpJo92xCJvpcgyiw1-5_2vZtzC-G9yMWPWMFul2GznZcPjtVQkFsK2TlY1LNMA5JFl5E4jB6lh1839npxVcZknjPvhlgArYZFy81UbmwfvmZBaznFfKh9EA]
2023-07-25T13:33:27 WARN : Retrying submission rate limiting check on server.
2023-07-25T13:33:30 WARN : Retrying submission rate limiting check on server.
2023-07-25T13:33:35 WARN : Retrying submission rate limiting check on server.
2023-07-25T13:33:41 WARN : Retrying submission rate limiting check on server.
2023-07-25T13:33:46 WARN : Retrying submission rate limiting check on server.
2023-07-25T13:33:51 WARN : Retrying submission rate limiting check on server.
2023-07-25T13:33:51 ERROR: Submission validation failed because of a system error : A server error occurred when retrieving rate limit information.. Please check validation reports for further information: /Users/pba10kg/Documents/workarea/paftol/K60.P0.KL_Handover/cpDNA/ENA_submissions/PAFTOL/EMBL_files_concatPT_76_still_to_do/genome/ERR4179965_pt/validate
uk.ac.ebi.ena.webin.cli.WebinCliException: Submission validation failed because of a system error : A server error occurred when retrieving rate limit information.. Please check validation reports for further information: /Users/pba10kg/Documents/workarea/paftol/K60.P0.KL_Handover/cpDNA/ENA_submissions/PAFTOL/EMBL_files_concatPT_76_still_to_do/genome/ERR4179965_pt/validate
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:303)
        at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:259)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:109)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:90)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: A server error occurred when retrieving rate limit information.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.checkGenomeSubmissionRatelimit(WebinCliExecutor.java:163)
        at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.validateSubmission(WebinCliExecutor.java:100)
        at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:286)
        ... 9 common frames omitted
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: A server error occurred when retrieving rate limit information.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.utils.ExceptionUtils.executeWithRestExceptionHandling(ExceptionUtils.java:55)
        at uk.ac.ebi.ena.webin.cli.service.RatelimitService.ratelimit(RatelimitService.java:66)
        at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.checkGenomeSubmissionRatelimit(WebinCliExecutor.java:161)
        ... 11 common frames omitted
Caused by: org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error
        at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:586)
        at uk.ac.ebi.ena.webin.cli.service.RatelimitService.lambda$null$0(RatelimitService.java:69)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.lambda$executeWithRetry$0(RetryUtils.java:65)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.executeWithRetry(RetryUtils.java:60)
        at uk.ac.ebi.ena.webin.cli.service.RatelimitService.lambda$ratelimit$2(RatelimitService.java:68)
        at uk.ac.ebi.ena.webin.cli.utils.ExceptionUtils.executeWithRestExceptionHandling(ExceptionUtils.java:45)
        ... 13 common frames omitted

**Comment by baileyp1** [comment]
Hello again, I just switched to using version 6.4.1. and the validation step works now so the error may be specific to version 6.5.0.
Paul B.
