### ISSUE TITLE
Invalid submission account user name or password

### ISSUE THREAD

**Issue by eritema** [enasequence/webin-cli#114]
Hi, while I'm able to access the archive through https://www.ebi.ac.uk/ena/submit/webin/login, validating a manifest file the username or password appear not valid. Password doesn't requires escaping. Any suggestion? Thank you

```
java -jar webin-cli-7.0.0.jar -context genome -validate -manifest meta1.txt -userName ega-yyy -password XXX
INFO : Your application version is 7.0.0
ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes.
INFO : Creating report file: /home/user/./webin-cli.report

cat /home/user/./webin-cli.report
2024-02-14T09:06:32 ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes.
uk.ac.ebi.ena.webin.cli.WebinCliException: Invalid submission account user name or password. Please try enclosing your password in single quotes.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.userError(WebinCliException.java:67)
        at uk.ac.ebi.ena.webin.cli.utils.ExceptionUtils.executeWithRestExceptionHandling(ExceptionUtils.java:47)
        at uk.ac.ebi.ena.webin.cli.service.LoginService.login(LoginService.java:79)
        at uk.ac.ebi.ena.webin.cli.WebinCli.getSubmissionAccount(WebinCli.java:681)
        at uk.ac.ebi.ena.webin.cli.WebinCli.<init>(WebinCli.java:132)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:109)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : [no body]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:660)
        at uk.ac.ebi.ena.webin.cli.service.LoginService.lambda$null$0(LoginService.java:82)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.lambda$executeWithRetry$0(RetryUtils.java:65)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.executeWithRetry(RetryUtils.java:60)
        at uk.ac.ebi.ena.webin.cli.service.LoginService.lambda$login$2(LoginService.java:81)
        at uk.ac.ebi.ena.webin.cli.utils.ExceptionUtils.executeWithRestExceptionHandling(ExceptionUtils.java:45)
        ... 13 common frames omitted
```

**Comment by cocathail** [comment]
Hi, it looks like you're having issues using an ega submission account. Please raise a helpdesk ticket via the EGA: helpdesk@ega-archive.org
