### ISSUE TITLE
read validator issue

### ISSUE THREAD

**Issue by macmanes** [enasequence/webin-cli#19]
Hello, 

I am having problems with the uploader - I am getting a validation error related to reads not being properly paired, however, I have confirmed that reads (Casava > 1.8) are properly paired. I am using v1.8.7 on Linux.  

### The error message
```
2019-07-17T19:48:33 INFO: File[1]: /mnt/lustre/macmaneslab/macmanes/pmel/reads/./Pmelanop_S1_L002_R1_001.fastq.gz: Collected 404531304 reads
2019-07-17T19:48:33 INFO: File[1]: /mnt/lustre/macmaneslab/macmanes/pmel/reads/./Pmelanop_S1_L002_R1_001.fastq.gz: Collected 1 read labels: [1]
2019-07-17T19:48:33 INFO: File[1]: /mnt/lustre/macmaneslab/macmanes/pmel/reads/./Pmelanop_S1_L002_R1_001.fastq.gz: Has possible dublicate(s): true
2019-07-17T19:48:33 INFO: File[2]: /mnt/lustre/macmaneslab/macmanes/pmel/reads/./Pmelanop_S1_L002_R2_001.fastq.gz: Collected 404531304 reads
2019-07-17T19:48:33 INFO: File[2]: /mnt/lustre/macmaneslab/macmanes/pmel/reads/./Pmelanop_S1_L002_R2_001.fastq.gz: Collected 1 read labels: [2]
2019-07-17T19:48:33 INFO: File[2]: /mnt/lustre/macmaneslab/macmanes/pmel/reads/./Pmelanop_S1_L002_R2_001.fastq.gz: Has possible dublicate(s): true
2019-07-17T19:48:33 INFO: Pairing percentage: 27.85%
2019-07-17T19:48:33 ERROR: Detected paired fastq submission with less than 30% of paired reads
2019-07-17T19:48:33 INFO: No duplicates confirmed.
```

### read headers and example of pairing
```
[6:50:07] ➜  reads zcat  Pmelanop_S1_L002_R1_001.fastq.gz| sed -n 40000001p
@E00526:138:H23F5CCX2:2:1114:4005:16586 1:N:0:GTGGTACC
[6:50:40] ➜  reads zcat  Pmelanop_S1_L002_R2_001.fastq.gz| sed -n 40000001p
@E00526:138:H23F5CCX2:2:1114:4005:16586 2:N:0:GTGGTACC
```

**Comment by macmanes** [comment]
A little more of the error, from log. I've also had this fail in the same way with another set of reads that are also properly paired. 

```
2019-07-17T10:28:39 INFO : Submission has not been validated previously.
2019-07-17T19:48:37 ERROR: Submission validation failed because of a user error: . Please check validation reports for further information: /mnt/lustre/macmaneslab/macmanes/pmel/
reads/reads/MSB_Mamm_273915/validate
uk.ac.ebi.ena.webin.cli.WebinCliException: Submission validation failed because of a user error: . Please check validation reports for further information: /mnt/lustre/macmanesla
b/macmanes/pmel/reads/reads/MSB_Mamm_273915/validate
        at uk.ac.ebi.ena.webin.cli.WebinCliException.validationError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.WebinCli.doValidation(WebinCli.java:219)
        at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:193)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:88)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException:
        at uk.ac.ebi.ena.webin.cli.WebinCliException.validationError(WebinCliException.java:83)
        at uk.ac.ebi.ena.webin.cli.rawreads.RawReadsWebinCli.validate(RawReadsWebinCli.java:144)
        at uk.ac.ebi.ena.webin.cli.WebinCli.doValidation(WebinCli.java:207)
        ... 11 common frames omitted
```

**Comment by raskoleinonen** [comment]
Thank you very much for reporting this validation error. Unfortunately, because of holiday absences we will not be able to investigate this immediately.

**Comment by macmanes** [comment]
Thank you for the response. Is there anything I can do to facilitate or track down the issue?

**Comment by raskoleinonen** [comment]
In the provided example, your read names are formatted correctly according to: 
https://ena-docs.readthedocs.io/en/latest/fileprep/reads.html#fastq-format

The claimed problem is ->

```
2019-07-17T19:48:33 INFO: Pairing percentage: 27.85%
2019-07-17T19:48:33 ERROR: Detected paired fastq submission with less than 30% of paired reads
2019-07-17T19:48:33 INFO: No duplicates confirmed.
```

There is an essentially arbitrary lower bound for the required pairing percentage (30%). 

We can do either of two things to fix this in Webin-CLI:
(i) investigate if there is something wrong with the pairing incl. investigation into the current effective pairing horizon.
(ii) Decrease the min. required pairing percentage.

The best person to look into either one is on an extended leave for the next month (summer time is generally good for absences as our submission volumes go down).

If I am correct then a possible workaround is to submit the files through:

programmatic Webin:
https://ena-docs.readthedocs.io/en/latest/reads/programmatic.html
or
interactive Webin:
https://ena-docs.readthedocs.io/en/latest/reads/interactive.html

I think the submitted files will be accepted for archival, but the processing would fail when the archived submitted files are being converted into a standard Fastq product. However in this case, the submitted file would be available for download once the runs are made public.

**Comment by raskoleinonen** [comment]
Closing the ticket due to inactivity.
