### ISSUE TITLE
Error assembly validation adding agp file

### ISSUE THREAD

**Issue by jesgomez** [enasequence/webin-cli#21]
Hi, 
I am running the webin-cli-1.8.8.jar validator on a scaffold genome assembly flatfile, that can be converted to chromosome coordinates via agp. However, I am getting the following error: 
ERROR: Submission validation failed because of a system error: org.mapdb.DBException$VolumeIOError
	at org.mapdb.volume.Volume.lockFile(Volume.java:498)
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:52)
	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
	at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
	at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
	at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
	at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidationPlan.execute(SubmissionValidationPlan.java:81)
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidator.validate(SubmissionValidator.java:15)
	at uk.ac.ebi.ena.webin.cli.assembly.SequenceWebinCli.validate(SequenceWebinCli.java:327)
	at uk.ac.ebi.ena.webin.cli.WebinCli.doValidation(WebinCli.java:207)
	at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:193)
	at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:88)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: Function not implemented
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1115)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.mapdb.volume.Volume.lockFile(Volume.java:490)
	... 23 more

If I only specify the flatfile in the manifest file the validator does not crash, but whenever I add the chromosome agp I get this error. 
Can anyone help me? 
Thank you, 
Jèssica

**Comment by snathanvj** [comment]
Hi Jessica,
  I think it is something related to your system memory or permission issue,
- could you please make sure you have enough storage(webin-cli has to create some mapping files ,which requires some space depends on your file size)
-if you have enough space left then please try running the webin-cli in diffrent folder.

   If the issue still persists, could you please upload the manifest file and the data files to your Webin upload folder (https://ena-docs.readthedocs.io/en/latest/fileprep/upload.html#upload-files) and we will investigate the error in full detail.

**Comment by jesgomez** [comment]
Hi,
Thank you for your answer. I do have enough space and after running the validator on a different directory, it keeps failing. I added all the data to my Webin upload folder, should I open a ticket specifying which is my username and the data I want to update?

**Comment by snathanvj** [comment]
Hi Jessica, 
     Thanks for the quick response, if these are the files you uploaded then no need to create another ticket, I will investigate and update you shortly. 

ALMOND_v2.0.chromosome_list.txt.gz
ALMOND_v2.0.chromosomes.agp.gz
ALMOND_v2.0.embl.gz
ALMOND_v2.0.manifest.txt

Thanks,
Senthil

**Comment by snathanvj** [comment]
java -jar webin-cli-1.8.8.jar -context genome -manifest ALMOND_v2.0.manifest.txt  -validate -username <username> -password <password>

It worked for me, I executed above command with the same files you submitted. Most likely it is issue with your system(could be space/permission issue or corrupted .contig file exists, not sure about the exact case).

So, please try deleting below files/folder manually and try again and let me know if the issue still persists.

genome/ALMONDv2/validate/.contig
genome/ALMONDv2/validate/.sequence

better delete the complete **genome** folder because if the execution terminated abnormally then the corrupted .contig and .sequence files may cause this issue.

**Comment by jesgomez** [comment]
Thank you, it was a problem with our file system, I run it from a different type of disk and now it worked.

**Comment by snathanvj** [comment]
Great. Thanks for the confirmation.
