### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by gibberwocky** [enasequence/webin-cli#29]
Attempting to validate a BAM file using webin-cli-3.0.1.jar, and receiving a stream of errors along the lines of the following:

`Exception in thread "pool-1-thread-404" java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
        at uk.ac.ebi.ena.readtools.webin.cli.rawreads.refs.CramReferenceInfo.lambda$confirmFileReferences$2(CramReferenceInfo.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by raskoleinonen** [comment]
Thank you very much for reporting the problem. We will investigate it but unfortunately have not yet had an opportunity to do so.

**Comment by raskoleinonen** [comment]
Haseeb has fixed this issue and it is waiting to be deployed in Webin-CLI.

**Comment by raskoleinonen** [comment]
Fix has been deployed in https://github.com/enasequence/webin-cli/releases/tag/v3.1.0
