### ISSUE TITLE
TranscriptomeAssemblyWebinCli Error

### ISSUE THREAD

**Issue by gthemoro** [enasequence/webin-cli#6]
From webin-cli version 1.0.12 I receive the following error message when I try to submit a trascriptome:
        

```
ERROR: java.lang.InstantiationException: uk.ac.ebi.ena.assembly.TranscriptomeAssemblyWebinCli
	at java.lang.Class.newInstance(Class.java:427)
	at uk.ac.ebi.ena.webin.cli.WebinCli.init(WebinCli.java:227)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:171)
Caused by: java.lang.NoSuchMethodException: uk.ac.ebi.ena.assembly.TranscriptomeAssemblyWebinCli.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 2 more
```

No problem with previous versions.
I'm using java version "1.8.0_171".

**Comment by raskoleinonen** [comment]
Could you please first try with the latest webin-cli release (1.0.15):

https://github.com/enasequence/webin-cli/releases/tag/V1.0.15

and please let us know if you still experience any problems

**Comment by gthemoro** [comment]
Yes, same problem.

```
ERROR: java.lang.InstantiationException: uk.ac.ebi.ena.assembly.TranscriptomeAssemblyWebinCli
	at java.lang.Class.newInstance(Class.java:427)
	at uk.ac.ebi.ena.webin.cli.WebinCli.init(WebinCli.java:260)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:197)
Caused by: java.lang.NoSuchMethodException: uk.ac.ebi.ena.assembly.TranscriptomeAssemblyWebinCli.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 2 more
```

**Comment by raskoleinonen** [comment]
Thank you. I have forwarded this problem to our developers.

**Comment by gthemoro** [comment]
Thanks.
Unfortunately now another error appears.

```
ERROR: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at uk.ac.ebi.ena.webin.cli.AbstractWebinCli.getSubmissionBundle(AbstractWebinCli.java:66)
	at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:289)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:198)
```

I tried with 2 different java versions and I receive the same error.

**Comment by raskoleinonen** [comment]
The problem is being investigated.

**Comment by raskoleinonen** [comment]
A new version has been released which we hope may have fixed the problem:

https://github.com/enasequence/webin-cli/releases/tag/v1.0.17

Our current testing process is inadequate. We are aware that we must improve it. In the meanwhile we will rapidly fix any reported issues and release new versions.

**Comment by raskoleinonen** [comment]
After more testing we have found that the 1.0.17 version is not working correctly either. We are releasing 1.0.18  imminently.

**Comment by raskoleinonen** [comment]
Version 1.0.18 has been released:

https://github.com/enasequence/webin-cli/releases/tag/v1.0.18

**Comment by gthemoro** [comment]
Now it seems to work fine,
thanks
