### ISSUE TITLE
Submission validation fails with "system error: Unable to empty directory" when using V4.0.0+

### ISSUE THREAD

**Issue by bmschoene** [enasequence/webin-cli#63]
Up until now, we have been using webin-cli version 3.1.0 for our submissions of HLA alleles, which worked fine. (This is on Windows 10.) We have incorporated it into our software [TypeLoader](https://github.com/DKMS-LSL/typeloader), which we and other labs use for submission of alleles of HLA & other related genes (KIR, MIC). 

In preparation of the upcoming deprecation, I'm trying to adjust our workflow to use V4.x, and am running into unexpected problems:

When I try to submit a project with V4.1.2 (or any other V4.x version), I get the following error in the webin-cli.report file:

```
2021-10-22T10:46:09 INFO : Submission has not been validated previously.
2021-10-22T10:46:09 ERROR: Submission validation failed because of a system error: Unable to empty directory C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_mixed_webinCLI\sequence\PRJEB48271_20211022104557_filesub\process. Please check validation reports for further information: C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_mixed_webinCLI\sequence\PRJEB48271_20211022104557_filesub\validate
uk.ac.ebi.ena.webin.cli.WebinCliException: Submission validation failed because of a system error: Unable to empty directory C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_mixed_webinCLI\sequence\PRJEB48271_20211022104557_filesub\process. Please check validation reports for further information: C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_mixed_webinCLI\sequence\PRJEB48271_20211022104557_filesub\validate
	at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:68)
	at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:216)
	at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:184)
	at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:95)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: Unable to empty directory C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_mixed_webinCLI\sequence\PRJEB48271_20211022104557_filesub\process
	at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:80)
	at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.createSubmissionDir(WebinCliExecutor.java:217)
	at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.validateSubmission(WebinCliExecutor.java:90)
	at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:200)
	... 11 common frames omitted
```

I don't understand this. The "process" subfolder is created by webin-cli, so it does not exist before webin-cli is called. webin-cli does create the folder just fine, so there should not be any access rights problems. Also, the folder is already empty. 

The "validate" subfolder is empty, as well, so there is no validation report I can check.

This was a submission to the test server, using a freshly created project containing only an existing sequence (HLA-A*01:01:01:01). 

The command used to call webin-cli was this:
```
java -jar "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\ENA_Webin_CLI\webin-cli-4.2.1.jar" -context sequence -manifest C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_HLA-A_webinCLItest\PRJEB48272_20211022104916_manifest.txt -inputDir "C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_HLA-A_webinCLItest" -outputDir "C:\Daten\local_data\TypeLoader\admin\projects\20211022_ADMIN_HLA-A_webinCLItest" -test
```
(plus the required userName, password and centerName)

I'm attaching the manifest file and flatfile I was trying to submit.

I have tried this with all of the available versions of webin-cli since 3.7.0. 3.7.0 passes without problems. Starting with 4.0.0, I get the error described above, in all V4.x versions.

Can you please look into this ASAP and give me instructions what to adjust in order to submit files using webin-cli V4.x? 

As the 3.x versions are supposed to be deprecated as of November 1st, this is urgent.

(I expected necessary adjustments, but not a complete break in the workflow without any lead how to adjust, hence the late issue. Sorry.)

**Comment by bmschoene** [comment]
Apparently, the problem occured because my workflow calles webin-cli twice, once with the `-validate` option and once with `-submit`. And starting from 4.0.0, webin-cli `-submit` seems to have problems deleting or overwriting the files created by itself during the `-validate` run.

So, now I run webin-CLI in `-validate` mode, check that the output is ok, then **delete the subfolder created during validation**, and only _then_ run webin-CLI in `-submit` mode. This works.

Not sure if this is the intended behaviour for webin-CLI, but it solves my problem, so I'll close this.
