### ISSUE TITLE
"ERROR: Invalid submission account user name or password." during submit but not validate

### ISSUE THREAD

**Issue by cabbagesofdoom** [enasequence/webin-cli#65]
Hi,

I am having an odd error with webin-cli. My manifest file validates fine, but when I run with `-submit` it tells me that the user name or password are invalid, despite being fine for `-validate` and the validation stage of `-submit`: 

```
java -jar ../webin-cli-4.2.1.jar -username 'Webin-XXXXX' -password 'YYYYYYY' -context genome -manifest RargV1.1.pri.txt -submit
INFO : Your application version is 4.2.1
INFO : Webin file submission services will be unavailable on Wednesday 10th of November 10.00 - 15.00 GMT. The downtime is required for essential maintenance. 
INFO : Creating report file: /srv/scratch/ausplant/Rhodamnia-Oct18/ena/v1.1.10xDecon/pri/./webin-cli.report
INFO : Submission has not been validated previously.
INFO : The submission has been validated successfully.
ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes. Failed to upload files to webin.ebi.ac.uk because of a user error.
```

Any ideas what's going on here or how to fix it? As both `-validate` and logging on to the portal works, I don't think it's actually a user name or password error. I've obviously masked my real username and password. My password does have a `*` but this did not cause issues for `-validate` once enclosed in single quotes.

Thanks,

Rich

PS. The more detailed error is:

```
2021-11-11T16:55:15 ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes. Failed to upload files to webin.ebi.ac.uk because of a user error.
uk.ac.ebi.ena.webin.cli.WebinCliException: Invalid submission account user name or password. Please try enclosing your password in single quotes. Failed to upload files to webin.ebi.ac.uk because of a user error.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.error(WebinCliException.java:88)
        at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:237)
        at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:188)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:95)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: Invalid submission account user name or password. Please try enclosing your password in single quotes.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.userError(WebinCliException.java:76)
        at uk.ac.ebi.ena.webin.cli.upload.FtpService.connect(FtpService.java:49)
        at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:232)
        ... 11 common frames omitted
```

**Comment by cabbagesofdoom** [comment]
Hi. 
I was able to get this to work on a computer connected to a different network, so I guess there was some file-upload-specific firewall issue that was being interpreted as a password issue?
Anyway, closing the issue. (But a more user-friendly process for ENA updates would be appreciated!)
Rich
