### ISSUE TITLE
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. connect timed out Failed to upload files to webin.ebi.ac.uk because of a system error.

### ISSUE THREAD

**Issue by genomics-ngsCBMSO** [enasequence/webin-cli#95]
Dear webin-cli,

I have been trying to upload some assemblies for the last days and always obtain the same error message:

java -jar webin-cli-6.3.0.jar -username Webin-XXX -password ********** -context genome -manifest manifest.txt -submit

INFO : Your application version is 6.3.0
INFO : 
A dedicated submission API for COVID-19 genomes is available here: <a href="https://www.ebi.ac.uk/ena/submit/webin-cli">https://www.ebi.ac.uk/ena/submit/webin-cli </a> <br>
INFO : Submission has not been validated previously.
INFO : Creating report file: Assemblies/./webin-cli.report
INFO : The submission has been validated successfully.
INFO : Connecting to FTP server : webin2.ebi.ac.uk
WARN : Retrying retrieving directory list from FTP server.
WARN : Retrying retrieving directory list from FTP server.
WARN : Retrying retrieving directory list from FTP server.
WARN : Retrying retrieving directory list from FTP server.
WARN : Retrying retrieving directory list from FTP server.
WARN : Retrying retrieving directory list from FTP server.
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. connect timed out Failed to upload files to webin.ebi.ac.uk because of a system error.
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. connect timed out Failed to upload files to webin.ebi.ac.uk because of a system error.

To be noticed that I HAD  a correct validation previous to the submission, although the app validates again when the command is submit. Here the previous validation:

INFO : Your application version is 6.3.0
INFO : 
A dedicated submission API for COVID-19 genomes is available here: <a href="https://www.ebi.ac.uk/ena/submit/webin-cli">https://www.ebi.ac.uk/ena/submit/webin-cli </a> <br>
INFO : The submission has been validated successfully.
INFO : Creating report file: /Assemblies/./webin-cli.report

Can you help me to correctly submit my assemblies?

Thank you in advance,
María (GENGS Facility, CBMSO, Madrid)

**Comment by sanjayibdc** [comment]
The same issue with me also, When used the older version like 6.0.0, The file transfer worked.

**Comment by genomics-ngsCBMSO** [comment]
As I was in kind of a hurry, tried everything that came to my mind and finally I got it working by using ascp. The command line that worked for me was:

java -jar webin-cli-6.3.0.jar -ascp -username XXX -password XXX -context genome -manifest manifest.txt -submit

In case you do not have it, it is compulsory for that order to go to have ascp installed and in your path.

Hope it works for you too!!
María

**Comment by samnooij** [comment]
I am getting the same error, which appears to me a duplicate of #53. I tried webin-cli version 6.0.0, 6.4.1 and 6.5.1. At first I thought it was a firewall problem, but I checked that ports 21, 40000 and 50000 are open. 
```bash
$ nc -z -v 193.62.193.143 21
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 193.62.193.143:21.
Ncat: 0 bytes sent, 0 bytes received in 0.02 seconds.

$ nc -z -v 193.62.193.143 40000
Ncat: Connected to 193.62.193.143:40000.
Ncat: 0 bytes sent, 0 bytes received in 0.02 seconds.

$ nc -z -v 193.62.193.143 50000
Ncat: Connected to 193.62.193.143:50000.
Ncat: 0 bytes sent, 0 bytes received in 0.02 seconds.
```

The error log is:
```
2023-08-09T15:54:59 ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.
uk.ac.ebi.ena.webin.cli.WebinCliException: Failed to upload files to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.error(WebinCliException.java:91)
        at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:328)
        at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:264)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:110)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: Failed to upload files to webin.ebi.ac.uk using FTP.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:71)
        at uk.ac.ebi.ena.webin.cli.upload.FtpService.changeToSubdir(FtpService.java:207)
        at uk.ac.ebi.ena.webin.cli.upload.FtpService.upload(FtpService.java:72)
        at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:324)
        ... 11 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:921)
        at org.apache.commons.net.ftp.FTPSClient._openDataConnection_(FTPSClient.java:622)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:790)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3441)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3371)
        at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:3116)
        at org.apache.commons.net.ftp.FTPClient.listDirectories(FTPClient.java:3213)
        at org.apache.commons.net.ftp.FTPClient.listDirectories(FTPClient.java:3165)
        at uk.ac.ebi.ena.webin.cli.upload.FtpService.lambda$changeToSubdir$6(FtpService.java:180)
        at uk.ac.ebi.ena.webin.cli.upload.FtpService.lambda$executeWithReconnect$15(FtpService.java:255)
        at uk.ac.ebi.ena.webin.cli.utils.RetryUtils.lambda$executeWithRetry$0(RetryUtils.java:65)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
```

**Comment by samnooij** [comment]
> As I was in kind of a hurry, tried everything that came to my mind and finally I got it working by using ascp. The command line that worked for me was:
> 
> java -jar webin-cli-6.3.0.jar -ascp -username XXX -password XXX -context genome -manifest manifest.txt -submit
> 
> In case you do not have it, it is compulsory for that order to go to have ascp installed and in your path.
> 
> Hope it works for you too!! María

I got it working with `ascp`, too.
Something like:
```bash
wget https://ak-delivery04-mul.dhe.ibm.com/sar/CMA/OSA/0adrj/0/ibm-aspera-connect_4.1.3.93_linux.tar.gz
```
and https://gist.github.com/mfansler/71f09c8b6c9a95ec4e759a8ffc488be3 can help you install Aspera.
(That is, download tarball, unpack, add to PATH and go!)

**Comment by grocanar** [comment]
I got the same problem for one of my user
when i capture a network trace i can see the following message

12:13:32.179731 IP ekeko.genoscope.cns.fr.54790 > hl-xfer-webin.ebi.ac.uk.ftp: Flags [.], ack 51, win 58, options [nop,nop,TS val 1126723035 ecr 726075720], length 0
12:13:32.179938 IP ekeko.genoscope.cns.fr.54790 > hl-xfer-webin.ebi.ac.uk.ftp: Flags [P.], seq 1:11, ack 51, win 58, options [nop,nop,TS val 1126723035 ecr 726075720
], length 10: FTP: AUTH TLS
12:13:32.180241 IP hl-xfer-webin.ebi.ac.uk.ftp > ekeko.genoscope.cns.fr.54790: Flags [.], ack 11, win 114, options [nop,nop,TS val 726075720 ecr 1126723035], length
0
12:13:32.180252 IP hl-xfer-webin.ebi.ac.uk.ftp > ekeko.genoscope.cns.fr.54790: Flags [P.], seq 51:163, ack 11, win 114, options [nop,nop,TS val 726075720 ecr 1126723
035], length 112: FTP: 502-Auth command is not supported.
