### ISSUE TITLE
ERROR: An exception occurred: Failed to retrieve file or directory information for: webin-cli/reads/sample/sample.fastq.gz. The submission has failed because of a system error.

### ISSUE THREAD

**Issue by timyerg** [enasequence/webin-cli#96]
I am facing this issue with 2 datasets using the latest version "webin-cli-6.3.0.jar" (tried also with 5.0), though I was able to upload one sample from one dataset which failed several times before. I am still getting this error with other samples.
I guess that there is some issue from the recipient part on the server, since one sample after several failed attempts was successfully uploaded after several attempts from my side without any changes from my side. 

```
2023-04-27T12:41:16 INFO : Submission has not been validated previously.
2023-04-27T12:41:16 INFO : Processing file /Samples_fastq/WT005.fastq.gz
2023-04-27T12:41:18 INFO : Collected 63934 reads [file: /Samples_fastq/WT005.fastq.gz]
2023-04-27T12:41:18 INFO : Collected 10 read labels: [099, 242, 223, 005, /Samples_fastq/WT005.fastq.gz, 028, 756, 329, 084, 629] [file: /Samples_fastq/WT005.fastq.gz]
2023-04-27T12:41:18 INFO : Has possible duplicate read name(s): false [file: /Samples_fastq/WT005.fastq.gz]
2023-04-27T12:41:18 INFO : The submission has been validated successfully.
2023-04-27T12:41:18 INFO : Connecting to FTP server : webin2.ebi.ac.uk
2023-04-27T12:41:19 INFO : Uploading file: /Samples_fastq/WT005.fastq.gz
2023-04-27T12:41:20 INFO : Files have been uploaded to webin2.ebi.ac.uk. 
2023-04-27T12:41:38 ERROR: An exception occurred: Failed to retrieve file or directory information for: webin-cli/reads/WT005/WT005.fastq.gz The submission has failed because of a system error.
uk.ac.ebi.ena.webin.cli.WebinCliException: An exception occurred: Failed to retrieve file or directory information for: webin-cli/reads/WT005/WT005.fastq.gz The submission has failed because of a system error.
	at uk.ac.ebi.ena.webin.cli.WebinCliException.error(WebinCliException.java:91)
	at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:342)
	at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:261)
	at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:109)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: An exception occurred: Failed to retrieve file or directory information for: webin-cli/reads/WT005/WT005.fastq.gz
	at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:83)
	at uk.ac.ebi.ena.webin.cli.service.SubmitService.processReceipt(SubmitService.java:188)
	at uk.ac.ebi.ena.webin.cli.service.SubmitService.doSubmission(SubmitService.java:124)
	at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:339)
	... 11 common frames omitted
```

**Comment by jocketuffing** [comment]
I have the same problem and have raised an issue on it.
I get the same error also when submitting with curl and using the submission portal.

**Comment by jocketuffing** [comment]
The test service responds as it should.

**Comment by timyerg** [comment]
@jocketuffing Please let me know if you will figure it out somehow...

**Comment by tottlefields** [comment]
> I have the same problem and have raised an issue on it. I get the same error also when submitting with curl and using the submission portal.

Phew, glad others are having the same problem. I can "see" my files in FileZilla so they are there, but submission via curl and webin portal both throw an exception - "Failed to retrieve file or directory information". 

Will follow this and hope it is fixed shortly.

Thanks.

**Comment by jocketuffing** [comment]
I feel exactly the same!

I can also see them in filezilla. And it is possible to browse in filezilla
but for some reason this browsing process does not work for ENA.
I think.

I found an old email from a submission that I cancelled, so I wrote in that
message about this problem. And I got a reply. Maybe that will get them
going 😀


Den tors 27 apr. 2023 kl 12:43 skrev Ellen Schofield <
***@***.***>:

**Comment by jocketuffing** [comment]
I feel exactly the same!

I can also see them in filezilla. And it is possible to browse in filezilla
but for some reason this browsing process does not work for ENA.
I think.

I found an old email from a submission that I cancelled, so I wrote in that
message about this problem. And I got a reply. Maybe that will get them
going 😀

Den tors 27 apr. 2023 kl 12:43 skrev Ellen Schofield <
***@***.***>:

**Comment by jocketuffing** [comment]
By the way the ascp option does not work either since it goes into this ftp listdir/file anyway

**Comment by BioWilko** [comment]
I'm running into the same, I've emailed a contact at ENA to make sure they're aware

**Comment by timyerg** [comment]
Good news!
Just launched my scripts again and it is working.

**Comment by jocketuffing** [comment]
Yeah thanks Timur and all, works for me too!
